SELECT * 
FROM (
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_pty' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_pty WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_org' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_org WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_ext_org' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_ext_org WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_int_org' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_int_org WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_fin_inst_int_org' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_fin_inst_int_org WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_org_name_hist' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_org_name_hist WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_pty_idfn' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_pty_idfn WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_pty_related' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_pty_related WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_type' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_type WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_class_val' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_class_val WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_inst' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_inst_text_hist' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst_text_hist WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_inst_stts_hist' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst_stts_hist WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_inst_stts_type' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst_stts_type WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_manuf_mdl' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_manuf_mdl WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_atm_chnl_inst' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_atm_chnl_inst WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_chnl_chnl_class_assoc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_chnl_class_assoc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_crncy' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_crncy WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_atm_chnl_crncy' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_atm_chnl_crncy WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name, 't_org_lvl' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_org WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_pty_chnl_inst' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_pty_chnl_inst WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_loc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_loc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_point_loc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_point_loc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_geospatial_loc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_geospatial_loc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_ip_address' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_ip_address WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,'t_chnl_inst_loc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst_loc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,'t_pty_loc' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_pty_loc WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N' UNION ALL
SELECT 'Merch1'(VARCHAR(30)) source_name,' t_chnl_inst_oper_hours' (VARCHAR(30)) AS t_table, COUNT(*) AS cnt FROM ft21_1_057_db_stg.ti_chnl_inst_oper_hours WHERE info_system_id IN (SELECT info_system_id FROM ft21_1_057_db_dwh.t_info_system WHERE info_system_type_cd = '057' AND deleted_flag = 'N') AND deleted_flag = 'N'       
   		) t
WHERE t.cnt = 0;	



